export const eventUrl = [
  {
    id: 1,
    name: "ISFEST",
    url: "/img/event/isfest.webp",
    logo: "/img/logo-isfest.webp",
    desc: "Information System Festival (ISFEST) is a HIMSI program designed to support the development of both academic and non-academic skills, open to students from all over Indonesia. ISFEST features a series of academic competitions related to the Information Systems study program, as well as non-academic competitions in the field of E-Sports. The event also includes a talk show with competent speakers in the field of Information Systems, presenting material that can be understood by all audiences to enhance their understanding of technology from an Information Systems perspective.",
  },
  {
    id: 2,
    name: "Sandhyakala",
    url: "/img/event/perprod.webp",
    logo: "/img/logo-perprod.webp",
    desc: 'PRASTAVANA 2024, organized by the Himpunan Mahasiswa Sistem Informasi, aims to introduce the Information Systems Study Program to new students with the theme "Transformation Towards The Future" and the tagline "Ignite Creativity, Create Innovation." This theme encourages new students to approach their academic challenges with enthusiasm and an open mindset, recognize their potential, and design their academic journey according to their goals. The tagline inspires them to enhance creativity and innovation, think beyond boundaries, create new solutions, and become change-makers in an academic environment that fosters experimentation and collaboration.',
  },
  {
    id: 3,
    name: "DISCO",
    url: "/img/event/disco.webp",
    logo: "/img/logo-disco.webp",
    desc: "D’Information System Community Outbound (DISCO) is an annual program organized by the Information Systems Student Association of Universitas Multimedia Nusantara (HIMSI-UMN) with the primary goal of enhancing solidarity and camaraderie among the entire Information Systems family, which includes faculty, alumni, and active students. DISCO was first held in 2010 by the first generation of HIMSI-UMN, previously known as D’Information System Community. This program has been passed down through generations, making DISCO one of the longest-running programs organized by HIMSI-UMN for over 11 years.",
  },
  {
    id: 4,
    name: "SOCIAL IS ME",
    url: "/img/event/sim.webp",
    logo: "/img/logo-sim.webp",
    desc: "Social Is Me (SIM) is a program by HIMSI UMN focused on community service. SIM involves social action activities aimed at helping communities achieve well-being, both in terms of environmental and social aspects. The activities under SIM are carried out through direct actions with the community, including practical work and social outreach. SIM relies on the initiative and concern of UMN students to create a more prosperous and synergistic Indonesian society.",
  },
  {
    id: 5,
    name: "FUNSPORT",
    url: "/img/event/funsport.webp",
    logo: "/img/logo-funsport.webp",
    desc: "FunSport is a competition for Information Systems students that takes place in both sports and e-sports events. This initiative aims to foster a competitive spirit and improve competitiveness among SI students in non-academic areas. Additionally, FunSport serves as a platform to enhance relationships and build connections among KBM SI members beyond their academic activities. By engaging in these competitions, students not only showcase their skills but also strengthen camaraderie and teamwork within the community.",
  },
  {
    id: 6,
    name: "SIBE",
    url: "/img/event/sibe.webp",
    logo: "/img/logo-sibe.webp",
    desc: "SIBE, formerly known as HIMFACT (HIMSI FACTORY), is a program under HIMSI designed as a business venture with the goal of contributing to the organization's funds. SIBE operates by selling a variety of merchandise, including apparel and lanyards. These items are available for purchase by all members of KBM SI as well as individuals outside of KBM SI. The program not only helps in generating additional revenue for the organization but also provides an opportunity for the wider community to engage with and support HIMSI through their merchandise. By offering these products, SIBE aims to promote the organization's identity and foster a sense of belonging among its members and supporters.",
  },
  {
    id: 7,
    name: "SIBERIAN WEEK",
    url: "/img/event/sibe-week.webp",
    logo: "/img/logo-siberianweek.webp",
    desc: "Siberian Week is a weekly training program designed to continuously enhance and develop the talents and interests of students in the Information Systems study program, focusing on both sports and e-sports. This initiative serves as a platform for students to refine their skills, build relationships, and strengthen connections within the KBM SI community. By providing regular training sessions and competitive opportunities, Siberian Week aims to foster personal growth, teamwork, and camaraderie among participants, while also promoting a deeper engagement with their fields of interest.",
  },
  {
    id: 8,
    name: "BIMBEL HIMSI",
    url: "/img/event/bimsi.webp",
    logo: "/img/logo-bimsi.webp",
    desc: "BIMBEL HIMSI is a program run by the Information Systems Student Association (HIMSI) at Universitas Multimedia Nusantara (UMN) aimed at helping Information Systems students develop their academic skills and providing teaching experience for interested students. This program is conducted online via Microsoft Teams with each session lasting 60 minutes. It is designed to address the needs of students who find it challenging to understand their courses and to provide an opportunity for those interested in teaching to develop their skills. Through BIMBEL HIMSI, students can receive flexible tutoring outside regular class hours.",
  },
  {
    id: 9,
    name: "COMPANY VISIT",
    url: "/img/event/comvis-2.webp",
    logo: "/img/logo-comvis.webp",
    desc: 'Company Visit 2024, organized by HIMSI UMN, aims to introduce Information Systems students to the working environment and enhance their understanding of companies. With the theme "Discovering IT Career Pathways: Exploring Opportunities and Challenges in Digital Business," this event provides a real-world view of the job market and career opportunities, as well as direct information about the field of information technology. Students will participate in presentations, department visits, and interactions with professionals, helping them to be better prepared for their future careers.',
  },
  {
    id: 10,
    name: "STUDI BANDING",
    url: "/img/event/stuban.webp",
    logo: "/img/logo-stuban.webp",
    desc: 'Studi Banding HIMSI UMN is an academic division program of HIMSI UMN aimed at expanding the knowledge and understanding of its members regarding the operations and activities of student associations at other universities. This event involves participants from the HIMSI Leadership Bootcamp (HLB) in semesters 1 and 3 under the theme "Together We Go Further." Its objectives are to build relationships between student associations, share information and experiences, and enhance the innovation and quality of future generations of the association. Activities include introductory sessions, presentations, Q&A, ice-breaking, inter-division sharing, group meals, campus tours, and photo sessions.',
  },
  {
    id: 11,
    name: "HIMSI ANNIVERSARY",
    url: "/img/event/anniv.webp",
    logo: "/img/anniv.webp",
    desc: "HIMSI ANNIVERSARY is held every September 9th to celebrate the founding of the Information Systems Student Association (HIMSI) at Universitas Multimedia Nusantara (UMN). During this event, there is typically a group meal to strengthen relationships among HIMSI members. Additionally, HIMSI members collect funds to be donated to community service organizations as a form of social contribution.",
  },
  {
    id: 12,
    name: "FORM ASPIRASI",
    url: "/img/event/aspirasi.webp",
    logo: "/img/aspirasi.webp",
    desc: "Form Aspirasi is a platform provided by HIMSI to collect aspirations from KBM SI and convey them to the Information Systems study program. This form is not just a regular document, but an exclusive stage for KBM SI to voice their hopes and concerns. Active participation in filling out this form is not merely a routine task, but a proactive step towards positive change. Each input given helps not only in evaluating the performance of the study program but also in strengthening solidarity among Active Students, Faculty, and Alumni.",
  },
  {
    id: 13,
    name: "HIMSI LEADERSHIP BOOTCAMP",
    url: "/img/event/hlb.webp",
    logo: "/img/logo-hlb.webp",
    desc: "HIMSI LEADERSHIP BOOTCAMP is a program designed to enhance the social and leadership skills of KBM SI. The program provides intensive training in communication, decision-making, and teamwork, as well as opportunities to interact and collaborate with peers. Through various activities and real-life simulations, participants learn to face challenges and manage conflicts, developing strong and responsible leadership qualities and mindset.",
  },
];
